# Generated by Django 6.1.1 on 2026-09-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_album_spotify_id_remove_artist_spotify_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='artists/banners/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='cutout',
            field=models.ImageField(blank=True, null=True, upload_to='artists/cutouts/'),
        ),
    ]
