"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env faylini o'qiydi va ichidagilarni "muhit o'zgaruvchisi" qilib qo'yadi.
# Parol, kalit kabi SIRLAR kodda emas, o'sha faylda turadi (.gitignore da bor).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# os.environ.get('X', default) = .env da X bo'lsa shuni ol, bo'lmasa default.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-_xv3car3y5t3snnr243$8q4=gw(68mds&%$#$c1*h5rksb2s=w',
)

# .env da DEBUG=False yozilsa o'chadi. Muhit o'zgaruvchilari har doim
# MATN bo'lgani uchun '1' bilan solishtiramiz.
DEBUG = os.environ.get('DEBUG', '1') == '1'

# Bo'sh qoldirilsa, DEBUG=True da Django localhost'ga o'zi ruxsat beradi.
# Serverga chiqarganda .env ga ALLOWED_HOSTS=sayt.uz deb yoziladi.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'music',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Butun saytga kirish uchun login TALAB qiladi.
    # AuthenticationMiddleware dan KEYIN turishi shart — u request.user
    # ni to'ldiradi, bu esa o'shani tekshiradi.
    # Istisnolar @login_not_required bilan belgilanadi (urls.py, views.py).
    #
    # Django niki emas, o'zimizniki: farqi shundaki, "qayerga bormoqchi
    # edingiz" ma'lumotini manzilga (?next=...) emas, sessiyaga yozadi.
    'music.middleware.KirishTalabMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # O'zimizniki: footer uchun janrlar ro'yxati
                'music.context_processors.footer',
                'music.context_processors.firebase',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# PostgreSQL yoki SQLite - .env ga qarab o'zi tanlaydi.
# .env da DB_NAME yozilgan bo'lsa -> PostgreSQL, aks holda SQLite.
# Ya'ni hozir hech narsa qilmasangiz ham sqlite bilan ishlab turaveradi.
if os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                # SQLite da bir vaqtda FAQAT BITTA yozuvchi bo'la oladi.
                # Server ishlab turganda terminaldan import qilsak,
                # ikkovi to'qnashib "database is locked" xatosi chiqadi.
                # timeout = qulf bo'shashini shuncha soniya kutib turadi.
                'timeout': 20,
            },
        }
    }


# --- Firebase (Google orqali kirish) ---
# Bu qiymatlar shablonga uzatiladi va brauzerda ochiq turadi —
# Firebase shunday ishlaydi, ular maxfiy emas.
# Haqiqiy himoya: brauzerdan kelgan token SERVERDA tekshiriladi
# (views.py dagi google_login) va faqat shundan keyin foydalanuvchi
# tizimga kiritiladi.
FIREBASE = {
    'apiKey': os.environ.get('FIREBASE_API_KEY', ''),
    'authDomain': os.environ.get('FIREBASE_AUTH_DOMAIN', ''),
    'projectId': os.environ.get('FIREBASE_PROJECT_ID', ''),
    'appId': os.environ.get('FIREBASE_APP_ID', ''),
    'messagingSenderId': os.environ.get('FIREBASE_SENDER_ID', ''),
}

# --- Kirish/chiqish sozlamalari ---
# LOGIN_URL = ruxsat talab qilinadigan sahifaga kirgan odam qayerga
#             yo'naltiriladi. Django'ning sukuti /accounts/login/ —
#             bizda bunday manzil yo'q, shuning uchun aniq ko'rsatamiz.
LOGIN_URL = 'music:login'
LOGIN_REDIRECT_URL = 'music:album_list'
LOGOUT_REDIRECT_URL = 'music:album_list'

# Tekshiruvchilar ro'yxati. Django ularni YUQORIDAN pastga sinab
# ko'radi. Bizniki birinchi: e-pochta bilan ham kirsa bo'lsin.
# Ikkinchisi Django'niki — admin paneli va boshqa joylar uchun kerak.
AUTHENTICATION_BACKENDS = [
    'music.auth_backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Spotify API kalitlari (.env dan olinadi).
# Bo'sh bo'lsa - Spotify funksiyalari ishlamaydi, qolgan sayt ishlayveradi.
# Qaysi musiqa xizmatidan import qilamiz: 'deezer' yoki 'spotify'.
# deezer  - kalit kerak emas, bepul, preview mp3 ham beradi
# spotify - kalit kerak + ilova egasida Premium bo'lishi shart (aks holda 403)
MUSIC_PROVIDER = os.environ.get('MUSIC_PROVIDER', 'deezer').lower()

SPOTIFY_CLIENT_ID = os.environ.get('SPOTIFY_CLIENT_ID', '')
SPOTIFY_CLIENT_SECRET = os.environ.get('SPOTIFY_CLIENT_SECRET', '')

# TheAudioDB — ijrochi rasmlari (cutout / banner / portret).
# Bo'sh qoldirilsa ochiq '2' test kaliti ishlatiladi (services/artwork.py).
AUDIODB_KEY = os.environ.get('AUDIODB_KEY', '')


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # Django nikidan meros olingan, faqat xabarlari o'zbekcha.
    # Sababi: Django ning o'zbekcha tarjima to'plamida aynan parol
    # xabarlari yo'q, LANGUAGE_CODE='uz' bo'lsa ham inglizcha chiqadi.
    {'NAME': 'music.password_validators.OxshashlikTekshiruvchi'},
    {
        'NAME': 'music.password_validators.UzunlikTekshiruvchi',
        'OPTIONS': {'min_length': 8},
    },
    {'NAME': 'music.password_validators.OddiyParolTekshiruvchi'},
    {'NAME': 'music.password_validators.RaqamliParolTekshiruvchi'},
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# collectstatic buyrug'i fayllarni shu yerga yig'adi (serverga chiqarishda)
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Loyihaning o'z CSS/JS fayllari (frontend shu yerga yozadi)
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []


# Media = FOYDALANUVCHI yuklagan fayllar (albom muqovalari, ijrochi rasmlari)
# MEDIA_URL  = brauzerdagi manzil boshlanishi: /media/covers/x.jpg
# MEDIA_ROOT = diskdagi papka: <loyiha>/media/
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
