# Generated by Django 6.1.1 on 2026-09-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotify_id',
        ),
        migrations.AddField(
            model_name='album',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='source',
            field=models.CharField(choices=[('manual', "Qo'lda"), ('spotify', 'Spotify'), ('deezer', 'Deezer')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='artist',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='source',
            field=models.CharField(choices=[('manual', "Qo'lda"), ('spotify', 'Spotify'), ('deezer', 'Deezer')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='source',
            field=models.CharField(choices=[('manual', "Qo'lda"), ('spotify', 'Spotify'), ('deezer', 'Deezer')], default='manual', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_album_external'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_artist_external'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_song_external'),
        ),
    ]
