# Generated by Django 6.1.1 on 2026-09-15 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_banner_artist_cutout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_albums', to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
        migrations.AddField(
            model_name='artist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_artists', to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
    ]
